# Generated by Django 5.0.1 on 2024-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0004_property_tenant_unit_rentalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='document_proofs',
            field=models.FileField(default=1, upload_to='tenant_documents/'),
            preserve_default=False,
        ),
    ]
