# Generated by Django 5.0.1 on 2024-01-08 10:05

import realestate_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0006_tenant_password_tenant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[realestate_app.models.email_validate])),
                ('contact', models.CharField(max_length=10, validators=[realestate_app.models.contact_validate])),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminRegistration',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
